### ISSUE TITLE
Option to use KC_POWER instead of KC_PWR

### ISSUE THREAD

**Issue by stephentuso** [ruiqimao/qmkbuilder#11]
Looks like `KC_PWR` doesn't work on Mac OS, but `KC_POWER` does ([source](https://github.com/tmk/tmk_keyboard/wiki/FAQ-Keymap)). As far as I can tell there isn't a way to set `KC_POWER` with this right now. A quick fix could be an option to manually enter a keycode, especially if there are some others that are missing from the GUI

**Comment by ruiqimao** [comment]
There is already an option to manually enter a keycode.

**Comment by stephentuso** [comment]
Thanks, didn't realize you could edit the code in the 'other' tab

Great work on this by the way, much easier than building manually
