### ISSUE TITLE
Did you forget to check in local.js?

### ISSUE THREAD

**Issue by NoahAndrews** [ruiqimao/qmkbuilder#3]
Both on Windows and Debian, `npm run build` produces this error: `errorify: Error: Cannot find module './local' from '/home/noah/qmkbuilder/src/const'`. It appears there should be a file called `local.js` in `src/const`, but there is none.

**Comment by ruiqimao** [comment]
There should be a `local.json` file in src/const that contains the URLs for the server `/build` route and the path to the folder of presets. I'll update that in the README.

**Comment by NoahAndrews** [comment]
Ah, gotcha. Thanks.

**Comment by ruiqimao** [comment]
It was left out on purpose because, well, every system has a different configuration. I've updated the README, so you should be able to create that file now.

**Comment by NoahAndrews** [comment]
Sounds good, closing.
