### ISSUE TITLE
S60-X RGB support

### ISSUE THREAD

**Issue by VinnyCordeiro** [ruiqimao/qmkbuilder#4]
I've made available at my [Github the base JSON files for the S60-X RGB keyboard](https://github.com/VinnyCordeiro/tmk_keyboard/tree/master/keyboard/s60-x_RGB). These includes standard ANSI layout, standard ISO layout and a generic layout, making visible all the keys available, in special the split backspace and both shift keys. The right shift key can be split like in JIS layout or like in HHKB layout.

**Comment by ruiqimao** [comment]
Added!

**Comment by VinnyCordeiro** [comment]
You are awesome! 😃
