### ISSUE TITLE
Why MACROS can't assign to a key?

### ISSUE THREAD

**Issue by PotatoJet** [ruiqimao/qmkbuilder#59]
For example,how to assign a macro to "A" key?
![image](https://user-images.githubusercontent.com/25473330/88940211-17025400-d2ba-11ea-8fd1-f3b2e5008df7.png)

**Comment by bignemez** [comment]
M() is what you need.
![image](https://user-images.githubusercontent.com/20778999/90607545-a50a9400-e201-11ea-89fc-680b8fc05efd.png)

**Comment by PotatoJet** [comment]
> M() is what you need.
> ![image](https://user-images.githubusercontent.com/20778999/90607545-a50a9400-e201-11ea-89fc-680b8fc05efd.png)
Thank you so much！I finally work it out！
