### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by AarynSmith** [ruiqimao/qmkbuilder#70]
Thank you for running this site for so many years. I just got into building my own keyboard and was using kbfirmware to build, and help me learn to use the source. Thanks for all the hard work you did, and good luck with your future project.

**Comment by andywarburton** [comment]
Same here! This tool was essential to me getting started with building my own firmware - there isn't another tool out there! How can we help you get up and running again?

**Comment by ruiqimao** [comment]
Thanks for the support! I've actually brought the website back online,
since there are actually more users than my analytics were reporting.

If you would like to host your own copy, the README now links a Docker
image that you can use to run the last live version.

**Comment by github1man** [comment]
You're back! I`m so happy! Don't leave us again!

**Comment by nooges** [comment]
@ruiqimao Can you specify a license for your code as requested in https://github.com/ruiqimao/qmkbuilder/issues/33? Thanks!
